src/Client.php
src/Parsing/Common/SummaryHelper.php
src/Parsing/Standard/ClassificationField.php
src/Parsing/Standard/Taxes.php
src/Product/Invoice/InvoiceV4.php
src/Product/Invoice/InvoiceV4Document.php
src/Product/Invoice/InvoiceV4LineItem.php
src/Product/Invoice/InvoiceV4LineItems.php

* :sparkles: add support for InvoiceV4, InvoiceV4Document, InvoiceV4LineItem & InvoiceV4LineItems
* :recycle: fix issues with summary helper
* :recycle: fix lingering typos from previous snake_case usage
* :bug: fix Taxes iterator

:sparkles: add support for Invoice V4

---

CHANGELOG.md
src/version.php

:bookmark: version 1.0.0-RC1

---

CHANGELOG.md
src/version.php

:bookmark: version 1.0.0-RC2

---

CHANGELOG.md
src/version.php

:bookmark: version 1.0.1

---

docs/extras/guide/invoices_v4.md
src/Parsing/Standard/StringField.php
src/Product/Invoice/InvoiceV4Document.php
tests/Parsing/Standard/StringFieldTest.php
tests/Product/Invoice/InvoiceV4Test.php

* :arrow_up: bump invoice version to 4.4
* :arrow_up: update invoice test
* :arrow_up: update test lib
* :recycle: add raw_value support

:arrow_up: update invoice version to 4.4

---

CHANGELOG.md
src/version.php

:bookmark: version 1.1.0

---

CHANGELOG.md
src/version.php

:bookmark: version 1.3.0

---

.github/workflows/unit-test.yml

:wrench: tweak CI on macOS

---

src/Client.php
src/Error/MindeeHttpException.php
src/Http/ResponseValidation.php
src/Parsing/Generated/GeneratedListField.php
src/Parsing/Generated/GeneratedObjectField.php
src/Product/Generated/GeneratedV1Document.php
src/Product/Generated/GeneratedV1Page.php
tests/Error/MindeeHttpExceptionTest.php
tests/Parsing/Common/AsyncPredictResponseTest.php

* :recycle: update error handling
* :bug: fix erroneous handling of lists in objects displays
* :memo: fix typos

:recycle: update error handling

---

src/Http/Endpoint.php
src/Input/Base64Input.php
src/Input/BytesInput.php
src/Input/FileInput.php
src/Input/LocalInputSource.php
src/Parsing/Common/Job.php
tests/Input/LocalInputSourceTest.php

* :bug: fix broken file closing for FileInputSource
* :recycle: remove redundant close parameter on the readContents() method

:bug: fix file close handling

---

CHANGELOG.md
src/version.php

:bookmark: version 1.3.1

---

docs/extras/guide/invoices_v4.md
src/Product/Invoice/InvoiceV4Document.php
tests/Product/Invoice/InvoiceV4Test.php
tests/Product/ProofOfAddress/ProofOfAddressV1Test.php

:sparkles: update Invoice to v4.5

---

src/Client.php
src/Error/MindeeHttpException.php
src/Input/Base64Input.php
src/Input/BytesInput.php
tests/Input/LocalInputSourceTest.php

See #36 
* :bug: fix improper handling of base64 files
* :bug: fix improper handling of bytes files
* :bug: fix error catching for CURL calls

:bug: fix bytes input sources

---

CHANGELOG.md
src/version.php

:bookmark: version 1.3.2

---

CHANGELOG.md
src/version.php

:bookmark: version 1.3.3

---

CHANGELOG.md
src/Parsing/Generated/GeneratedObjectField.php
src/Product/Generated/GeneratedV1Document.php
src/Product/Generated/GeneratedV1Page.php

* :bug: fix invalid parsing of numeric fields in generated api (#41)
* :recycle: clean up field reading syntaxes
* :memo: fix changelog typo

:bug: fix improper handling of number fields on Generated APIs

---

CHANGELOG.md
src/version.php

:bookmark: version 1.3.4

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.4.0

---

src/Input/URLInputSource.php
tests/Input/LocalInputSourceTest.php
tests/Input/URLInputSourceTest.php

* :bug: fix url checking wrongfully using modern function to check for https #46 
* :recycle: fix url source test being tested in the wrong spot

:bug: replace invalid syntax for php < 8

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.4.1

---

CHANGELOG.md

:memo: fix changelog

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.4.2

---

src/Http/Endpoint.php
src/Input/URLInputSource.php
tests/Input/URLInputSourceTestRegression.php

* :bug: fix URL sources being improperly injected in CURL call
* :recycle: add full integration test
Addresses the third problem raised in #46

:bug: fix urls improperly being handled

---

docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/financial_document_v1.md
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/Receipt/ReceiptV5Document.php
tests/Product/Receipt/ReceiptV5Test.php

* :sparkles: update receipt API to v5.2
* :sparkles: update financial doc API to 1.7
* :recycle: update test lib

:sparkles: update financial document to 1.7 & receipt to 5.2

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.5.0

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.6.0

---

docs/code_samples/us_mail_v2_async.txt
docs/extras/guide/us_mail_v2.md
src/Parsing/Common/SummaryHelper.php
src/Parsing/Standard/BooleanField.php
src/Parsing/Standard/LocaleField.php
src/Product/Us/UsMail/UsMailV2.php
src/Product/Us/UsMail/UsMailV2Document.php
src/Product/Us/UsMail/UsMailV2RecipientAddress.php
src/Product/Us/UsMail/UsMailV2RecipientAddresses.php
src/Product/Us/UsMail/UsMailV2SenderAddres.php
tests/Product/Us/UsMail/UsMailV2Test.php

* :sparkles: add support for boolean fields
* :sparkles: add support for US Mail V2
* :bug: fix locale display issue

:sparkles: add support for boolean fields & add us mail v2

---

docs/extras/guide/us_mail_v2.md
src/Product/Us/UsMail/UsMailV2Document.php
src/Product/Us/UsMail/UsMailV2SenderAddress.php

:bug: fix typo in class name

---

.github/workflows/docs.yml
CHANGELOG.md

:memo: fix documentation action

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.8.0

---

src/Http/Endpoint.php
tests/Product/Cropper/CropperExtraTestRegression.php

* :bug: fix cropper extra being improperly called
* :recycle: add regression test for cropper extra

:bug: fix cropper extra

---

src/Parsing/Standard/CompanyRegistrationField.php

* :recycle: add type on company registration print

:recycle: update company registration display

---

composer.json

See #69 
* :bug: fix composer warning triggered due to improper path given to CLI

:bug: fix composer warning due to improper bin path given to installer

---

src/Client.php
src/Input/Base64Input.php
src/Input/BytesInput.php
src/Input/FileInput.php
src/Input/LocalInputSource.php
src/Input/PathInput.php
tests/Input/LocalInputSourceTest.php

* :sparkles: add pdf fixing utility
* :recycle: tweak some input source loading
**TODO:**

:sparkles: add pdf fixing utility

---

bin/MindeeCLIDocuments.php

:recycle: update cli entries

---

CHANGELOG.md
src/version.php

:bookmark: version 1.9.0

---

docs/code_samples/invoices_v4_async.txt
docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/invoices_v4.md
src/Product/InternationalId/InternationalIdV2Document.php
src/Product/MultiReceiptsDetector/MultiReceiptsDetectorV1Document.php
src/Product/Receipt/ReceiptV5Document.php

:recycle: add async invoice test file & update some doc

---

docs/code_samples/invoices_v4_async.txt
docs/extras/guide/bank_account_details_v2.md
docs/extras/guide/bank_check_v1.md
docs/extras/guide/barcode_reader_v1.md
docs/extras/guide/carte_grise_v1.md
docs/extras/guide/carte_vitale_v1.md
docs/extras/guide/cropper_v1.md
docs/extras/guide/eu_driver_license_v1.md
docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/financial_document_v1.md
docs/extras/guide/idcard_fr_v2.md
docs/extras/guide/international_id_v2.md
docs/extras/guide/invoices_v4.md
docs/extras/guide/license_plates_v1.md
docs/extras/guide/multi_receipts_detector_v1.md
docs/extras/guide/passport_v1.md
docs/extras/guide/proof_of_address_v1.md
docs/extras/guide/resume_v1.md
docs/extras/guide/us_driver_license_v1.md
docs/extras/guide/us_healthcare_cards_v1.md
docs/extras/guide/us_w9_v1.md
src/Product/InternationalId/InternationalIdV2Document.php
src/Product/MultiReceiptsDetector/MultiReceiptsDetectorV1Document.php
src/Product/Receipt/ReceiptV5Document.php

* :memo: Fix a lot of typos in the guide documentation
* :recycle: add async invoice sample code

:memo: fix a lot of md documentation

---

README.md
docs/custom_v1.md

:memo: fix broken documentation URLs

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.10.0

---

bin/MindeeCLICommand.php
src/Client.php
src/Http/Endpoint.php
src/Input/PredictOptions.php
src/Parsing/Common/Document.php
src/Parsing/Common/Extras/Extras.php
src/Parsing/Common/Extras/FullTextOcrExtra.php
tests/Parsing/Common/Extras/ExtrasIntegrationFunctional.php
tests/Parsing/Common/Extras/FullTextOcrExtraTest.php

:sparkles: add support for full text OCR extraction

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.11.0

---

.github/workflows/check-unused-dependencies.yml
composer.json
tests/Extraction/InvoiceSplitterAutoExtractionTestFunctional.php
tests/TestingUtilities.php

* :recycle: remove spatie/pdf-to-image
* :recycle: fix functional tests to test for levenshtein

:recycle: remove unneeded pdf-to-image depdency

---

examples/InvoiceSplitterAutoExtractionExample.php
examples/MultiReceiptsAutoExtractionExample.php

:memo: fix example files

---

docs/bill_of_lading_v1.md
docs/energy_bill_fra_v1.md
docs/expense_receipts_v5.md
docs/financial_document_v1.md
docs/invoices_v4.md
docs/nutrition_facts_v1.md
docs/payslip_fra_v2.md
docs/us_mail_v2.md
examples/MultiReceiptsAutoExtractionExample.php
src/Parsing/Standard/DateField.php
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/Invoice/InvoiceV4Document.php
tests/Parsing/Standard/DateFieldTest.php
tests/Product/Invoice/InvoiceV4Test.php

:sparkles: add support for financial document v1.10 & invoice v4.8

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.12.0

---

docs/business_card_v1.md
docs/code_samples/business_card_v1_async.txt
docs/code_samples/delivery_notes_v1_async.txt
docs/code_samples/ind_passport_v1_async.txt
docs/delivery_notes_v1.md
docs/financial_document_v1.md
docs/ind_passport_v1.md
docs/invoices_v4.md
docs/resume_v1.md
src/Input/EnqueueAndParseMethodOptions.php
src/Product/BusinessCard/BusinessCardV1.php
src/Product/BusinessCard/BusinessCardV1Document.php
src/Product/DeliveryNote/DeliveryNoteV1.php
src/Product/DeliveryNote/DeliveryNoteV1Document.php
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/Ind/IndianPassport/IndianPassportV1.php
src/Product/Ind/IndianPassport/IndianPassportV1Document.php
src/Product/Invoice/InvoiceV4Document.php
src/Product/Resume/ResumeV1Document.php
src/Product/Resume/ResumeV1ProfessionalExperience.php
src/Product/Resume/ResumeV1ProfessionalExperiences.php
tests/Product/BusinessCard/BusinessCardV1Test.php
tests/Product/DeliveryNote/DeliveryNoteV1Test.php
tests/Product/Ind/IndianPassport/IndianPassportV1Test.php

* :sparkles: add support for business cards V1
* :sparkles: add support for delivery note V1.1
* :sparkles: add support for indian passport V1
* :sparkles: add support for resume V1.1

:sparkles: add support for business cards, delivery notes, indian passport & update resume

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.13.0

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.14.0

---

docs/code_samples/workflow_execution.txt

:memo: fix workflow execution code sample

---

CHANGELOG.md
CLI.md
README.md
docs/custom_v1.md
docs/getting_started.md
src/version.php

:bookmark: Version 1.15.0

---

src/Input/EnqueueAndParseMethodOptions.php

:recycle: increase async retry timers

---

CHANGELOG.md
src/PDF/PDFCompressor.php
src/version.php

:bookmark: Version 1.16.0

---

tests/ClientTest.php

:recycle: add test coverage for failed jobs

---

src/Http/BaseApi.php
src/Http/BaseEndpoint.php

What it says on the tin.
Tested on metabase.

:bug: harmonize OS names across client libraries

---

bin/MindeeCLIDocuments.php
docs/expense_receipts_v5.md
docs/financial_document_v1.md
docs/idcard_fr_v2.md
docs/ind_passport_v1.md
docs/international_id_v2.md
docs/invoice_splitter_v1.md
docs/invoices_v4.md
docs/resume_v1.md
src/Product/DeliveryNote/DeliveryNoteV1Document.php
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/FinancialDocument/FinancialDocumentV1LineItem.php
src/Product/FinancialDocument/FinancialDocumentV1LineItems.php
src/Product/Invoice/InvoiceV4Document.php
src/Product/Invoice/InvoiceV4LineItem.php
src/Product/Invoice/InvoiceV4LineItems.php
src/Product/Receipt/ReceiptV5Document.php
src/Product/Receipt/ReceiptV5LineItem.php
src/Product/Receipt/ReceiptV5LineItems.php

:recycle: upgrade descriptions, documentation & CLI products

---

docs/energy_bill_fra_v1.md
src/Product/Fr/EnergyBill/EnergyBillV1Document.php
src/Product/Fr/EnergyBill/EnergyBillV1EnergyUsage.php
src/Product/Fr/EnergyBill/EnergyBillV1EnergyUsages.php
src/Product/Fr/EnergyBill/EnergyBillV1MeterDetail.php
src/Product/Us/HealthcareCard/HealthcareCardV1Document.php

:sparkles: bump FR EnergyBillV1 to V1.2 & US HealthcareCardV1 to V1.1

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.17.0

---

src/Parsing/Common/Extras/CropperExtra.php
src/Parsing/Common/Extras/Extras.php

:bug: fix null objects being returned in extras

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.17.1

---

docs/financial_document_v1.md
docs/invoices_v4.md
docs/us_healthcare_cards_v1.md
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/Invoice/InvoiceV4Document.php
src/Product/Us/HealthcareCard/HealthcareCardV1Copay.php
src/Product/Us/HealthcareCard/HealthcareCardV1Copays.php
src/Product/Us/HealthcareCard/HealthcareCardV1Document.php
tests/Product/FinancialDocument/FinancialDocumentV1Test.php
tests/Product/Us/HealthcareCard/HealthcareCardV1Test.php

:sparkles: add support for Findoc V1.12, Invoices V4.10, US Healthcare Cards V1.2

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.18.0

---

src/Parsing/Common/Ocr/Ocr.php
tests/Parsing/Common/Ocr/OcrTest.php

:sparkles: add ocr line extraction from regex

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.19.0

---

.github/workflows/_test-integrations.yml
.github/workflows/_test-units.yml
src/Client.php
src/Http/WorkflowEndpoint.php
src/Input/WorkflowOptions.php
tests/Workflow/WorkflowTestFunctional.php

:sparkles: add support for rag param in workflow executions

---

CHANGELOG.md
src/version.php

:bookmark: Version 1.20.0

---

src/Client.php
src/Http/BaseApi.php
src/Http/BaseEndpoint.php
src/Http/Endpoint.php
src/Image/ImageCompressor.php
src/Input/PredictMethodOptions.php
src/Parsing/Common/Document.php
src/Parsing/Common/Extras/Extras.php
src/Parsing/Common/Extras/RAGExtra.php
src/Parsing/Common/Inference.php
tests/Workflow/WorkflowTestFunctional.php

* :sparkles: add support for RAG polling
* :sparkles: add extras accessor from inference

:sparkles: add support for workflow polling

---

CHANGELOG.md
docs/code_samples/workflow_polling.txt
src/version.php
tests/test_code_samples.sh

:bookmark: Version 1.21.0

---

docs/energy_bill_fra_v1.md
docs/expense_receipts_v5.md
docs/financial_document_v1.md
docs/ind_passport_v1.md
docs/invoices_v4.md
docs/us_healthcare_cards_v1.md
docs/us_mail_v3.md
src/Parsing/Common/Inference.php
src/Parsing/Standard/AddressField.php
src/Product/FinancialDocument/FinancialDocumentV1Document.php
src/Product/Ind/IndianPassport/IndianPassportV1Document.php
src/Product/InternationalId/InternationalIdV2Document.php
src/Product/Invoice/InvoiceV4Document.php
src/Product/InvoiceSplitter/InvoiceSplitterV1Document.php
src/Product/Receipt/ReceiptV5Document.php
src/Product/Us/HealthcareCard/HealthcareCardV1Copay.php
src/Product/Us/HealthcareCard/HealthcareCardV1Copays.php
src/Product/Us/HealthcareCard/HealthcareCardV1Document.php
tests/ClientTest.php
tests/Parsing/Common/PredictResponseTest.php
tests/Product/Ind/IndianPassport/IndianPassportV1Test.php
tests/Product/Us/HealthcareCard/HealthcareCardV1Test.php

:sparkles: add support for address fields + update products

---

CHANGELOG.md
README.md
src/Parsing/V2/Field/InferenceFields.php
src/version.php

:bookmark: Version 1.23.0-rc1
